version: '3'

services:
  postgres_master:
    container_name: postgres_master
    build: ./master
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./data-slave:/var/lib/postgresql/data-slave
      - ./init-script/config/postgres.conf:/etc/postgresql/postgresql.conf
      - ./init-script/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./init-script:/etc/postgresql/init-script
      - ./createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  postgres_slave:
    container_name: postgres_slave
    build: ./slave
    restart: always
    volumes:
      - ./data-slave:/var/lib/postgresql/data
      - ./init-script/config/postgres.conf:/etc/postgresql/postgresql.conf
      - ./init-script/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "127.0.0.1:5433:5432"
    depends_on:
      - postgres_master
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres